name: Get changed folders

on:
  push:
    branches:
      - main

jobs:
  get-changed-folders:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: changed folders
      uses: Stockopedia/action-get-changed-files@v1
      id: get_changed
      with:
        foldersOnly: true # to only include folders in the output
        format: json # either json, csv or newline
    - name: Echo
      run: echo ${{ steps.get_changed.outputs.changed }}
    # - name: Checkout code
    #   uses: actions/checkout@v2

    # - name: Get changed folders
    #   id: changed_folders
    #   run: |
    #     folders=$(git diff --name-only HEAD~1 HEAD | xargs -I{} dirname {} | sort -u)
    #     echo "::set-output name=folders::$folders"
      
    # - name: Use the output
    #   run: |
    #     echo "The following folders have been changed:"
    #     echo "${{ steps.changed_folders.outputs.folders }}"
