name: Get changed folders

on:
  push:
    branches:
      - main

jobs:
  get-changed-folders:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: changed folders
      uses: Stockopedia/action-get-changed-files@v1
      id: get_changed
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        ignore: "**/+(.github)"
        foldersOnly: false 
        format: json # either json, csv or newline
    - name: Echo
      run: |
          values=()
          for val in $(echo '${{ steps.get_changed.outputs.changed }}' | jq -r '.[]'); do
            if [[ "$val" == dbt/core* ]]; then
              value=${val#dbt/core/}
              values+=(${value%%/*})
            fi
          done
          unique_values=($(echo "${values[@]}" | tr ' ' '\n' | sort -u | tr '\n' ' '))
          for val in "${unique_values[@]}"; do
            echo "Unique Value: $val"
          done
